name: PR Validation

on:
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: self-hosted   # we’ll register your MacBook as the runner
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Build Docker Image
        run: docker build -t my-automation .

      - name: Run Automation in Container
        run: docker run --rm my-automation
